### ISSUE TITLE
Send <text> rather than index number

### ISSUE THREAD

**Issue by rherban** [chriszelazo/homebridge-switcheroo#1]
Just found this tonight and figured it'd be a good use for RGB lights attached to an ESP8266 that have a variety of custom light modes (rainbow, theater, tv, etc) that the default light color picker just doesn't cover.

Unfortunately, sending an index number isn't useful for my situation, so I tweaked my local code to send the text instead.  
line 94: reqUrl = this.baseUrl + '/' + this.multiswitch[idx];

I'm not sure if this could become a config option or not, but wanted to say thanks.

**Comment by chrszlz** [comment]
Hey sorry I never saw this, the repo was updated so you can define custom URL paths now. I built this originally for my simple setup which was kind of naive. 
Hope it helps!
